require('dotenv').config();
const mongoose = require('mongoose');
const Anime = require('./models/Anime');

const animes = [
  {
    title: "One Piece",
    description: "Monkey D. Luffy refuses to let anyone or anything stand in the way of his quest to become the king of all pirates. With a course charted for the treacherous waters of the Grand Line and beyond, this is one captain who'll never give up until he's claimed the greatest treasure on Earth: the Legendary One Piece!",
    year: 1999,
    rating: 9.0,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx21-tXMN3Y20PIL9.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg",
    genres: ["Action", "Adventure", "Comedy", "Drama", "Fantasy"],
    status: "ongoing",
    views: 1540300
  },
  {
    title: "Naruto: Shippuden",
    description: "It has been two and a half years since Naruto Uzumaki left Konohagakure, the Hidden Leaf Village, for intense training following events which fueled his desire to be stronger. Now Akatsuki, the mysterious organization of elite rogue ninja, is closing in on their grand plan which may threaten the safety of the entire shinobi world.",
    year: 2007,
    rating: 8.3,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx1735-1m3M4sR0Tq2r.png",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/1735-ZOSIqE78aR2O.jpg",
    genres: ["Action", "Comedy"],
    status: "completed",
    views: 1205000
  },
  {
    title: "Attack on Titan",
    description: "Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called titans, forcing humans to hide in fear behind enormous concentric walls. What makes these giants truly terrifying is that their taste for human flesh is not born out of hunger but what appears to be out of pleasure.",
    year: 2013,
    rating: 9.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16498-m5ZMNtFiHc7j.png",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/16498-8jpFCOcDmnei.jpg",
    genres: ["Action", "Drama", "Fantasy", "Mystery"],
    status: "completed",
    views: 2100000
  },
  {
    title: "Jujutsu Kaisen",
    description: "Idly indulging in baseless paranormal activities with the Occult Club, high schooler Yuuji Itadori spends his days at either the clubroom or the hospital, where he visits his bedridden grandfather. However, this leisurely lifestyle soon takes a turn for the bizarre when he unknowingly encounters a cursed item.",
    year: 2020,
    rating: 8.7,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415-bbBWj4pEFseh.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/113415-jQBSkxWAAk83.jpg",
    genres: ["Action", "Drama", "Supernatural"],
    status: "ongoing",
    views: 1850000
  },
  {
    title: "Demon Slayer: Kimetsu no Yaiba",
    description: "Ever since the death of his father, the burden of supporting the family has fallen upon Tanjirou Kamado's shoulders. Though living impoverished on a remote mountain, the Kamado family are able to enjoy a relatively peaceful and happy life. One day, Tanjirou decides to go down to the local village to make a little money selling charcoal.",
    year: 2019,
    rating: 8.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-PEn1CTc93DQl.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/101922-YlzjhBEXzTz3.jpg",
    genres: ["Action", "Adventure", "Drama", "Fantasy", "Supernatural"],
    status: "ongoing",
    views: 1720000
  },
  {
    title: "Death Note",
    description: "A shinigami, as a god of death, can kill any person—provided they see their victim's face and write their victim's name in a notebook called a Death Note. One day, Ryuk, bored by the shinigami lifestyle and interested in seeing how a human would use a Death Note, drops one into the human realm.",
    year: 2006,
    rating: 9.0,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1535-lawCWHqiQsFq.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/1535-umVz9O9VwJWa.jpg",
    genres: ["Mystery", "Psychological", "Supernatural", "Thriller"],
    status: "completed",
    views: 2500000
  },
  {
    title: "Fullmetal Alchemist: Brotherhood",
    description: "After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse are left in a catastrophic new reality. Ignoring the alchemical principle banning human transmutation, the boys attempted to bring their recently deceased mother back to life.",
    year: 2009,
    rating: 9.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx5114-KjtQz9AImRFe.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/5114-q0V5URebphSG.jpg",
    genres: ["Action", "Adventure", "Drama", "Fantasy"],
    status: "completed",
    views: 1400000
  },
  {
    title: "Solo Leveling",
    description: "Ten years ago, the Gate appeared and connected the real world with the realm of magic and monsters. To combat these vile beasts, ordinary people received superhuman powers and became known as Hunters.",
    year: 2024,
    rating: 8.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151807-m1gX3iwfIsLu.png",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/151807-y7rKEDQAd1lJ.jpg",
    genres: ["Action", "Adventure", "Fantasy"],
    status: "ongoing",
    views: 950000
  },
  {
    title: "Hunter x Hunter (2011)",
    description: "Hunter x Hunter is set in a world where Hunters exist to perform all manner of dangerous tasks like capturing criminals and bravely searching for lost treasures in uncharted territories. Twelve-year-old Gon Freecss is determined to become the best Hunter possible in hopes of finding his father.",
    year: 2011,
    rating: 9.0,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11061-sIpBprXispM7.png",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/11061-FwXw7R2L6c5G.jpg",
    genres: ["Action", "Adventure", "Fantasy"],
    status: "completed",
    views: 1800000
  },
  {
    title: "Steins;Gate",
    description: "Eccentric scientist Rintarou Okabe has a never-ending thirst for scientific exploration. Together with his ditzy but well-meaning friend Mayuri Shiina and his roommate Itaru Hashida, Rintarou founds the Future Gadget Laboratory in the hopes of creating technological innovations that baffle the human psyche.",
    year: 2011,
    rating: 9.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx9253-y5BfLnlT0e8h.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/9253-uJcfJmXnB82B.jpg",
    genres: ["Drama", "Psychological", "Sci-Fi", "Thriller"],
    status: "completed",
    views: 1200000
  },
  {
    title: "Chainsaw Man",
    description: "Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils in order to pay off his crushing debts.",
    year: 2022,
    rating: 8.6,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx127230-NuFVFOI3aokW.png",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/127230-0OEEFp2tqNvm.jpg",
    genres: ["Action", "Comedy", "Drama", "Supernatural"],
    status: "ongoing",
    views: 1600000
  },
  {
    title: "Spy x Family",
    description: "Corrupt politicians, frenzied nationalists, and other warmongering forces constantly jeopardize the thin veneer of peace between neighboring countries Ostania and Westalis. In spite of their plots, renowned spy Twilight successfully fulfills dangerous missions one after another in the hope that no child will have to experience the horrors of war.",
    year: 2022,
    rating: 8.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx140960-Yl5glEUMbNiQ.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/140960-9M2Ntzc4w0fQ.jpg",
    genres: ["Action", "Comedy", "Slice of Life"],
    status: "ongoing",
    views: 1300000
  },
  {
    title: "Sword Art Online",
    description: "In the year 2022, virtual reality has progressed by leaps and bounds, and a massive online role-playing game called Sword Art Online (SAO) is launched. With the aid of NerveGear technology, players can control their avatars within the game using nothing but their own thoughts.",
    year: 2012,
    rating: 7.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11757-Q9P2zjCPICq5.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/11757-vL41A1aGg8C4.jpg",
    genres: ["Action", "Adventure", "Fantasy", "Romance"],
    status: "completed",
    views: 1750000
  },
  {
    title: "My Hero Academia",
    description: "The appearance of quirks, newly discovered super powers, has been steadily increasing over the years, with 80 percent of humanity possessing various abilities from manipulation of elements to shapeshifting. This leaves the remainder of the world completely powerless, and Izuku Midoriya is one such individual.",
    year: 2016,
    rating: 8.0,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21459-oZMZ7vwgs3E4.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21459-hO1V8v431M1b.jpg",
    genres: ["Action", "Adventure", "Comedy"],
    status: "ongoing",
    views: 1450000
  },
  {
    title: "Vinland Saga",
    description: "Young Thorfinn grew up listening to the stories of old sailors that had traveled the ocean and reached the place of legend, Vinland. It's said to be warm and fertile, a place where there would be no need for fighting—not at all like the frozen village in Iceland where he was born, and certainly not like his current life as a mercenary.",
    year: 2019,
    rating: 8.9,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101348-2x7i5F8Z0Oam.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/101348-1C1X7n9l1kYx.jpg",
    genres: ["Action", "Adventure", "Drama"],
    status: "ongoing",
    views: 850000
  },
  {
    title: "Cyberpunk: Edgerunners",
    description: "Night City is a sprawling, dangerous metropolis full of cyber-enhanced individuals where one's life is only worth as much as the chrome they are rocking. Life for David Martinez is difficult; he is struggling to make ends meet and keep up with his high-end school.",
    year: 2022,
    rating: 8.8,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx120377-2qV23ZJ1LpUu.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/120377-qD1K22P6D40k.jpg",
    genres: ["Action", "Sci-Fi", "Drama"],
    status: "completed",
    views: 1100000
  },
  {
    title: "Frieren: Beyond Journey's End",
    description: "The demon king has been defeated, and the victorious hero party returns home before disbanding. The four—mage Frieren, hero Himmel, priest Heiter, and warrior Eisen—reminisce about their decade-long journey as the moment to bid each other farewell arrives.",
    year: 2023,
    rating: 9.3,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx154587-sA0rP5U6gXkZ.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/154587-n29Zidw3q0zB.jpg",
    genres: ["Adventure", "Drama", "Fantasy"],
    status: "ongoing",
    views: 1050000
  },
  {
    title: "Bleach",
    description: "Ichigo Kurosaki is an ordinary high schooler—until his family is attacked by a Hollow, a corrupt spirit that seeks to devour human souls. It is then that he meets a Soul Reaper named Rukia Kuchiki, who gets injured while protecting Ichigo's family from the assailant.",
    year: 2004,
    rating: 8.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx269-QkI2aFp5pEa8.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/269-xT0H34X6H2cI.jpg",
    genres: ["Action", "Adventure", "Supernatural"],
    status: "completed",
    views: 1150000
  },
  {
    title: "One Punch Man",
    description: "The seemingly ordinary and unimpressive Saitama has a rather unique hobby: being a hero. In order to pursue his childhood dream, he trained relentlessly for three years—and lost all of his hair in the process.",
    year: 2015,
    rating: 8.7,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21087-ezHjQkF31o9x.png",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21087-sS6kLtz2V9pW.jpg",
    genres: ["Action", "Comedy", "Sci-Fi"],
    status: "completed",
    views: 1950000
  },
  {
    title: "Mob Psycho 100",
    description: "Eighth-grader Shigeo Kageyama has tapped into his inner wellspring of psychic prowess at a young age. But the power quickly proves to be a liability when he realizes the potential danger in his skills. Choosing to suppress his power, Shigeo's only present use for his ability is to impress his longtime crush, Tsubomi.",
    year: 2016,
    rating: 8.7,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21507-Oa60580rE9v8.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21507-5ZfG1Vwz0gO4.jpg",
    genres: ["Action", "Comedy", "Supernatural", "Slice of Life"],
    status: "completed",
    views: 980000
  },
  {
    title: "Tokyo Ghoul",
    description: "A sinister threat is invading Tokyo: flesh-eating ghouls who appear identical to humans and blend into their population. Reserved college student Ken Kaneki buries his nose in books and avoids the news of the growing crisis.",
    year: 2014,
    rating: 7.8,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20605-N8R01zY9nKqV.png",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20605-B949F0DqXFKn.jpg",
    genres: ["Action", "Drama", "Horror", "Mystery", "Psychological", "Supernatural"],
    status: "completed",
    views: 1890000
  },
  {
    title: "Cowboy Bebop",
    description: "In the year 2071, humanity has colonized several of the planets and moons of the solar system leaving the now uninhabitable surface of planet Earth behind. The Inter Solar System Police attempts to keep peace in the galaxy, aided in part by outlaw bounty hunters, referred to as Cowboys.",
    year: 1998,
    rating: 8.9,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1-CXtrrkMtZ8ND.png",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/1-T3PJUjF6wq2W.jpg",
    genres: ["Action", "Adventure", "Sci-Fi"],
    status: "completed",
    views: 850000
  },
  {
    title: "Code Geass",
    description: "In the year 2010, the Holy Empire of Britannia is establishing itself as a dominant military nation, starting with the conquest of Japan. Renamed to Area 11 after its swift defeat, Japan has seen significant resistance against these tyrants in an attempt to regain independence.",
    year: 2006,
    rating: 8.9,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1575-dMF68L0pTz9L.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/1575-iX1yvXQW8H9n.jpg",
    genres: ["Action", "Drama", "Sci-Fi"],
    status: "completed",
    views: 1250000
  },
  {
    title: "Neon Genesis Evangelion",
    description: "In the year 2015, the world stands on the brink of destruction. Humanity's last hope lies in the hands of Nerv, a special agency under the United Nations, and their Evangelions, giant machines capable of defeating the Angels who herald Earth's ruin.",
    year: 1995,
    rating: 8.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx30-B1Xo499yK847.png",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/30-3qD6z3Fq3p2X.jpg",
    genres: ["Action", "Drama", "Mecha", "Psychological", "Sci-Fi"],
    status: "completed",
    views: 920000
  },
  {
    title: "Dragon Ball Z",
    description: "Five years after winning the World Martial Arts tournament, Gokuu is now living a peaceful life with his wife and son. This changes, however, with the arrival of a mysterious enemy named Raditz who presents himself as Gokuu's long-lost brother.",
    year: 1989,
    rating: 8.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx813-w4n3q73oJ9jA.png",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/813-rSAn9Z6O8H0K.jpg",
    genres: ["Action", "Adventure", "Comedy", "Fantasy"],
    status: "completed",
    views: 1350000
  },
  {
    title: "Monster",
    description: "Dr. Kenzo Tenma is a brilliant neurosurgeon with a glittering future ahead of him. But his world spins out of control when he chooses to save the life of a young boy over that of the town's mayor, inadvertently unleashing a psychopathic mastermind into the world.",
    year: 2004,
    rating: 8.8,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx19-9n6G8A2mPl0t.png",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/19-2KqOlwU3F6Lh.jpg",
    genres: ["Drama", "Mystery", "Psychological", "Thriller"],
    status: "completed",
    views: 310000
  },
  {
    title: "Mushishi",
    description: "Mushi are the most primitive life forms in the world, existing without any purposes or purposes other than simply being. Ginko is a Mushi Master who travels around investigating these ethereal entities to help people plagued by their supernatural effects.",
    year: 2005,
    rating: 8.7,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx457-3kL9omN8PzQ1.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/457-9OkLmNv4K2pQ.jpg",
    genres: ["Adventure", "Fantasy", "Mystery", "Slice of Life", "Supernatural"],
    status: "completed",
    views: 195000
  },
  {
    title: "Haikyuu!!",
    description: "Inspired after watching a volleyball ace nicknamed the Little Giant in action, small-statured Shouyou Hinata revives the volleyball club at his middle school. Despite a crushing defeat by the King of the Court, Tobio Kageyama, Hinata vows to surpass him in high school.",
    year: 2014,
    rating: 8.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20464-9mdKscCg4M0H.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20464-7O1N9p7X4K3R.jpg",
    genres: ["Sports", "Comedy", "Drama"],
    status: "completed",
    views: 1420000
  },
  {
    title: "Your Lie in April",
    description: "Kousei Arima is a piano prodigy who loses his ability to hear the sound of his own piano after his mother passes away. His monotonous life changes completely when he meets Kaori Miyazono, an eccentric and free-spirited violinist who drags him back into the spotlight.",
    year: 2014,
    rating: 8.6,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20665-ZfN0WwW1nO6Q.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20665-7wXyQ9wF4L2E.jpg",
    genres: ["Drama", "Music", "Romance"],
    status: "completed",
    views: 1100000
  },
  {
    title: "Clannad: After Story",
    description: "Clannad: After Story follows Tomoya Okazaki and Nagisa Furukawa as they graduate from high school and experience the emotional roller coaster of growing up, facing severe personal tragedies, and learning the true meaning of family.",
    year: 2008,
    rating: 8.9,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx4181-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/4181-7Xm9O8vW3L4z.jpg",
    genres: ["Drama", "Romance", "Supernatural", "Slice of Life"],
    status: "completed",
    views: 450000
  },
  {
    title: "Kaguya-sama: Love is War",
    description: "At the renowned Shuchiin Academy, Miyuki Shirogane and Kaguya Shinomiya are the top student council representatives. Proud and elite, both are madly in love, but neither wants to confess first. Thus begins a highly intellectual war to force the other to confess!",
    year: 2019,
    rating: 8.6,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101921-9mNzO9R2Xk8f.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/101921-7N8mOqW3L4zZ.jpg",
    genres: ["Comedy", "Romance", "Psychological"],
    status: "completed",
    views: 1350000
  },
  {
    title: "Violet Evergarden",
    description: "The Great War finally came to an end after four long years. Caught up in the bloodshed was Violet Evergarden, a young girl raised for the sole purpose of decimating enemy lines. She begins working as an Auto Memory Doll to understand the final words told to her by the person she held dearest.",
    year: 2018,
    rating: 8.7,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21856-Z8mN9O2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21856-7Xm9O8vW3L4z.jpg",
    genres: ["Drama", "Fantasy"],
    status: "completed",
    views: 950000
  },
  {
    title: "Re:Zero - Starting Life in Another World",
    description: "When Subaru Natsuki leaves the convenience store, the last thing he expects is to be wrenched from his everyday life and dropped into a fantasy world. Things change drastically when he discovers he has the ability to rewind time by dying.",
    year: 2016,
    rating: 8.3,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21355-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21355-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Drama", "Fantasy", "Psychological", "Thriller"],
    status: "ongoing",
    views: 1080000
  },
  {
    title: "That Time I Got Reincarnated as a Slime",
    description: "Thirty-seven-year-old Satoru Mikami is a typical corporate worker, who is perfectly content with his monotonous lifestyle. After falling victim to a random assailant on the streets, he wakes up in an unfamiliar fantasy realm—as a slime monster with unique skills.",
    year: 2018,
    rating: 8.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101280-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/101280-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Comedy", "Fantasy"],
    status: "ongoing",
    views: 1150000
  },
  {
    title: "Parasyte: The Maxim",
    description: "All of a sudden, alien parasites arrive on Earth, swiftly infiltrating humanity by boring into the brains of vulnerable targets. One parasite tries to enter the brain of high school student Shinichi Izumi, but ends up burrowing into his right hand instead.",
    year: 2014,
    rating: 8.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20623-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20623-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Drama", "Horror", "Psychological", "Sci-Fi"],
    status: "completed",
    views: 920000
  },
  {
    title: "Gintama",
    description: "The Amanto, aliens from outer space, have invaded Earth and taken over feudal Japan. As a result, a prohibition on swords has been established, and the samurai of Japan are treated with disregard. However, Gintoki Sakata still possesses the heart of a samurai.",
    year: 2006,
    rating: 9.0,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx918-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/918-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Comedy", "Sci-Fi", "Drama"],
    status: "completed",
    views: 640000
  },
  {
    title: "Erased",
    description: "When tragedy is about to strike, Satoru Fujinuma finds himself sent back several minutes before the accident occurs. The detached manga artist has taken advantage of this powerful yet mysterious phenomenon, which he calls Revival, to save many lives.",
    year: 2016,
    rating: 8.3,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21234-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21234-7Xm9O8vW3L4z.jpg",
    genres: ["Mystery", "Psychological", "Supernatural", "Thriller"],
    status: "completed",
    views: 1220000
  },
  {
    title: "Made in Abyss",
    description: "An enormous chasm known as the Abyss is the only unexplored place in the world. Generations of bold adventurers, known as Cave Raiders, have descended into its depths. Riko, an orphan girl, dreams of becoming a legendary Cave Raider like her mother.",
    year: 2017,
    rating: 8.7,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx97986-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/97986-7Xm9O8vW3L4z.jpg",
    genres: ["Adventure", "Drama", "Fantasy", "Mystery", "Sci-Fi"],
    status: "completed",
    views: 480000
  },
  {
    title: "The Promised Neverland",
    description: "Surrounded by a forest and a gated entrance, Grace Field House is inhabited by orphans happily living together as one big family, looked after by their Mama, Isabella. However, all illusions are shattered when the children discover the dark truth behind their existence.",
    year: 2019,
    rating: 8.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101759-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/101759-7Xm9O8vW3L4z.jpg",
    genres: ["Mystery", "Psychological", "Thriller", "Horror"],
    status: "completed",
    views: 1400000
  },
  {
    title: "Gurren Lagann",
    description: "Simon and Kamina were born and raised in a deep, underground village, hidden from the legendary surface. When a giant robot crashes through the ceiling accompanied by a fiery girl named Yoko, the duo uses a mysterious drill core device to break out to the surface world.",
    year: 2007,
    rating: 8.7,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx2001-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/2001-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Comedy", "Mecha", "Sci-Fi"],
    status: "completed",
    views: 590000
  },
  {
    title: "Fate/Zero",
    description: "With the promise of granting any wish, the omnipotent Holy Grail triggered three wars in the past, each too cruel and fierce to leave a victor. Despite that, the wealthy Einzbern family is confident that the Fourth Holy Grail War will be different.",
    year: 2011,
    rating: 8.6,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx10087-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/10087-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Fantasy", "Supernatural", "Thriller"],
    status: "completed",
    views: 610000
  },
  {
    title: "Samurai Champloo",
    description: "Fuu Kasumi is a young and clumsy waitress who spends her days working in a peaceful teahouse. When she accidentally spills a drink on a group of samurai, she ends up rescuing two rogue swordsmen who agree to help her find a samurai who smells of sunflowers.",
    year: 2004,
    rating: 8.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx205-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/205-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Comedy"],
    status: "completed",
    views: 520000
  },
  {
    title: "Psycho-Pass",
    description: "In the 22nd century, Japan enforces the Sibyl System, an objective means of measuring the chemical mental states of citizens. This measurement is known as the Psycho-Pass. When an individual's Criminal Coefficient rises too high, they are hunted down by Inspectors and Enforcers.",
    year: 2012,
    rating: 8.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx13601-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/13601-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Psychological", "Sci-Fi", "Thriller"],
    status: "completed",
    views: 740000
  },
  {
    title: "Black Clover",
    description: "Asta and Yuno are orphans raised together at a church on the outskirts of the Clover Kingdom. In a world where everyone has magic powers, Asta was born completely without them, while Yuno grew up as a prodigy with immense magical capacity.",
    year: 2017,
    rating: 8.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx97940-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/97940-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Comedy", "Fantasy"],
    status: "completed",
    views: 1250000
  },
  {
    title: "Kill la Kill",
    description: "Ryuuko Matoi wields a large scissor blade and searches for the murderer of her father. Her search leads her to Honnouji Academy, a competitive high school where the student council president distributes powerful Goku Uniforms that grant superhuman abilities.",
    year: 2013,
    rating: 8.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx18671-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/18671-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Comedy", "Ecchi", "Sci-Fi"],
    status: "completed",
    views: 680000
  },
  {
    title: "Durarara!!",
    description: "Ryuugamine Mikado is a young boy who longs for the exciting city life. At the invitation of his childhood friend Masaomi, he transfers to a school in Ikebukuro, Tokyo, a city filled with dangerous rumors, anonymous gangs, and urban legends like the headless Black Rider.",
    year: 2010,
    rating: 8.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx6746-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/6746-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Mystery", "Supernatural"],
    status: "completed",
    views: 490000
  },
  {
    title: "Land of the Lustrous",
    description: "In a mysterious future, crystalline organisms called Gems inhabit a world where they must constantly defend themselves against the Lunarians, an alien race who targets them to turn their shattered bodies into jewelry.",
    year: 2017,
    rating: 8.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx98707-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/98707-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Drama", "Fantasy", "Mystery", "Sci-Fi"],
    status: "completed",
    views: 145000 // Underrated Gem
  },
  {
    title: "Odd Taxi",
    description: "Kotakawa is an eccentric, relatively blunt 41-year-old walrus taxi driver who lives a quiet life. However, his conversations with his eccentric passengers lead him straight into the middle of a complex missing high school girl mystery case.",
    year: 2021,
    rating: 8.7,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx128544-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/128544-7Xm9O8vW3L4z.jpg",
    genres: ["Mystery", "Psychological", "Comedy", "Thriller"],
    status: "completed",
    views: 210000 // Underrated
  },
  {
    title: "Baccano!",
    description: "During the early 1930s in Chicago, a transcontinental train begins a legendary trail of blood across the country. Simultaneously, an alchemy experiment from centuries prior threatens to trigger a turf war among mafia families.",
    year: 2007,
    rating: 8.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx2251-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/2251-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Mystery", "Supernatural", "Comedy"],
    status: "completed",
    views: 280000
  },
  {
    title: "March Comes in Like a Lion",
    description: "Rei Kiriyama is an elite, 17-year-old professional shogi player who struggles under intense pressure from both the shogi community and his adoptive family. He moves into an apartment in Tokyo, where he gradually opens up after meeting three kind sisters.",
    year: 2016,
    rating: 8.6,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21353-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21353-7Xm9O8vW3L4z.jpg",
    genres: ["Drama", "Slice of Life"],
    status: "completed",
    views: 230000
  },
  {
    title: "Ping Pong the Animation",
    description: "Smile and Peco are high school friends who have known each other since childhood, playing table tennis together at a local sports venue. Despite their distinct personalities, their talent surfaces as they prepare for a grueling inter-high school sports tournament.",
    year: 2014,
    rating: 8.6,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20607-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20607-7Xm9O8vW3L4z.jpg",
    genres: ["Sports", "Drama", "Psychological"],
    status: "completed",
    views: 120000 // Masterpiece Underrated
  },
  {
    title: "The Disastrous Life of Saiki K.",
    description: "Kusuo Saiki possesses a vast array of supernatural powers, including telepathy and psychokinesis. Sounds amazing? Not to Kusuo, who desires nothing more than an ordinary, peaceful life without dealing with any disruptions.",
    year: 2016,
    rating: 8.6,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21804-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21804-7Xm9O8vW3L4z.jpg",
    genres: ["Comedy", "Supernatural", "Slice of Life"],
    status: "completed",
    views: 890000
  },
  {
    title: "Toradora!",
    description: "Ryuuji Takasu is a gentle high school student with a fierce face that makes people label him a delinquent. He crosses paths with Taiga Aisaka, a tiny but incredibly fierce girl known as the Palmtop Tiger, leading to an unlikely romantic pact.",
    year: 2008,
    rating: 8.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx4224-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/4224-7Xm9O8vW3L4z.jpg",
    genres: ["Comedy", "Romance", "Drama", "Slice of Life"],
    status: "completed",
    views: 950000
  },
  {
    title: "Anohana: The Flower We Saw That Day",
    description: "A group of six childhood friends drifts apart after one of them, Meiko 'Menma' Honma, dies in an accident. Years later, the leader of the group, Jinta Yadomi, becomes withdrawn, only to be visited by Menma's ghost asking to fulfill a forgotten wish.",
    year: 2011,
    rating: 8.3,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx9989-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/9989-7Xm9O8vW3L4z.jpg",
    genres: ["Drama", "Romance", "Supernatural", "Slice of Life"],
    status: "completed",
    views: 720000
  },
  {
    title: "Barakamon",
    description: "Seishuu Handa is an arrogant up-and-coming calligrapher who punches a veteran critic for calling his work unoriginal. As punishment, his father exiles him to a remote rural island where Handa must find his own artistic inspiration among chaotic villagers.",
    year: 2014,
    rating: 8.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20722-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20722-7Xm9O8vW3L4z.jpg",
    genres: ["Comedy", "Slice of Life"],
    status: "completed",
    views: 290000
  },
  {
    title: "Nichijou - My Ordinary Life",
    description: "Nichijou focuses on the daily antics of a trio of childhood friends—Mio, Yuuko, and Mai—whose paths closely intertwine with a young prodigy scientist, her robot caretaker, and a talking cat, making everyday life absolutely absurd.",
    year: 2011,
    rating: 8.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx10165-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/10165-7Xm9O8vW3L4z.jpg",
    genres: ["Comedy", "Slice of Life"],
    status: "completed",
    views: 410000
  },
  {
    title: "Banana Fish",
    description: "Aslan Jade Callenreese, known as Ash Lynx, is a ruthless runaway raised by the mafia godfather Dino Golzine. Ash begins investigating a mysterious phrase 'Banana Fish' that his brother muttered after returning from war, leading to dangerous criminal conspiracies.",
    year: 2018,
    rating: 8.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx100388-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/100388-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Drama", "Thriller", "Mystery"],
    status: "completed",
    views: 530000
  },
  {
    title: "Hellsing Ultimate",
    description: "There exist creatures of darkness that plague the night, devouring any unfortunate human trapped in their grasp. Hellsing is an organization dedicated to destroying these supernatural forces, utilizing their ultimate secret weapon: the ancient vampire Alucard.",
    year: 2006,
    rating: 8.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx777-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/777-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Horror", "Supernatural"],
    status: "completed",
    views: 430000
  },
  {
    title: "Noragami",
    description: "Yato is a minor deity who styles himself as a delivery god, dreaming of millions of worshippers. Without a single shrine to his name, his fortunes change when a human middle school girl saves him from a car accident, loose bonding their souls.",
    year: 2014,
    rating: 8.0,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20447-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20447-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Comedy", "Supernatural"],
    status: "completed",
    views: 980000
  },
  {
    title: "Dorohedoro",
    description: "In the grimy metropolis known as the Hole, a magic clan tests their arts on vulnerable citizens. Kaiman is a man cursed with a reptile head and absolute immunity to magic, searching for the sorcerer responsible to break his spell.",
    year: 2020,
    rating: 8.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx105228-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/105228-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Comedy", "Fantasy", "Horror"],
    status: "completed",
    views: 240000
  },
  {
    title: "Ashita no Joe",
    description: "Joe Yabuki is a troubled, drifting young man who uses raw physical strength to survive the rough slums of Tokyo. A former boxing coach notices his potential and vows to transform him into Japan's ultimate professional boxing icon.",
    year: 1970,
    rating: 8.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx2402-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/2402-7Xm9O8vW3L4z.jpg",
    genres: ["Sports", "Drama"],
    status: "completed",
    views: 45000 // Vintage Masterpiece
  },
  {
    title: "Mononoke",
    description: "The Medicine Seller is a deadly mysterious master of the occult who travels across feudal Japan to exorcise malevolent spirits known as Mononoke. However, to slay them, he must first uncover their Form, Truth, and Reason.",
    year: 2007,
    rating: 8.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx2246-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/2246-7Xm9O8vW3L4z.jpg",
    genres: ["Mystery", "Horror", "Psychological", "Supernatural"],
    status: "completed",
    views: 85000 // Highly Underrated Visual Masterpiece
  },
  {
    title: "Texhnolyze",
    description: "In the dystopian underground city of Lux, rival factions fight for control over the crime-ridden territory. Ichise, an underground prize fighter, loses his limbs and undergoes experimental Texhnolyze cybernetic enhancement.",
    year: 2003,
    rating: 7.8,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx26-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/26-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Drama", "Psychological", "Sci-Fi"],
    status: "completed",
    views: 65000 // Deep Dark Hidden Gem
  },
  {
    title: "Black Lagoon",
    description: "Rokurou Okajima is a standard Japanese businessman who is captured by a mercenary group known as the Lagoon Company operating out of a lawless crime city in Thailand. He decides to throw away his past corporate life and join their smuggling ranks.",
    year: 2006,
    rating: 8.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx889-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/889-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Drama", "Thriller"],
    status: "completed",
    views: 460000
  },
  {
    title: "Overlord",
    description: "The final hour of the popular virtual reality game Yggdrasil has arrived. However, Momonga, a powerful wizard and master of the dark guild Ainz Ooal Gown, finds himself fully conscious within the game even after the servers shut down.",
    year: 2015,
    rating: 8.0,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20832-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20832-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Fantasy"],
    status: "ongoing",
    views: 890000
  },
  {
    title: "Great Teacher Onizuka",
    description: "Eikichi Onizuka is a 22-year-old former biker gang leader who reforms his life to achieve his supreme goal: becoming the greatest high school teacher in all of Japan, handling problematic students using unorthodox street methods.",
    year: 1999,
    rating: 8.7,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx245-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/245-7Xm9O8vW3L4z.jpg",
    genres: ["Comedy", "Drama", "Slice of Life"],
    status: "completed",
    views: 510000
  },
  {
    title: "Kuroko's Basketball",
    description: "The Generation of Miracles is a legendary middle school basketball squad that dominated the national tournament circuit. Upon entering high school, the team's hidden phantom sixth player, Tetsuya Kuroko, aims to bring his new team to the top.",
    year: 2012,
    rating: 8.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11771-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/11771-7Xm9O8vW3L4z.jpg",
    genres: ["Sports", "Comedy"],
    status: "completed",
    views: 820000
  },
  {
    title: "Bleach: Thousand-Year Blood War",
    description: "The peace is suddenly shattered when warning sirens wail through the Soul Society. Residents are disappearing without a trace, and a new group of powerful Quincy warriors emerges to wage an all-out war against the Soul Reapers.",
    year: 2022,
    rating: 9.0,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx142877-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/142877-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Fantasy", "Supernatural"],
    status: "ongoing",
    views: 750000
  },
  {
    title: "Chihayafuru",
    description: "Chihaya Ayase is a tomboyish girl who lives under the shadow of her successful sister. She discovers a deep, life-changing passion for competitive Karuta—a traditional Japanese card game—after meeting a quiet transfer student.",
    year: 2011,
    rating: 8.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx10800-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/10800-7Xm9O8vW3L4z.jpg",
    genres: ["Drama", "Sports", "Romance"],
    status: "completed",
    views: 130000 // Underrated
  },
  {
    title: "The Eminence in Shadow",
    description: "Cid Kagenou does not want to be a boring protagonist or a flashy boss. He prefers mastermind operations from the deep shadows. Reincarnated into a magical universe, he constructs an elite secret organization to dismantle a fake cult, which turns out to be real.",
    year: 2022,
    rating: 8.3,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx130298-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/130298-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Comedy", "Fantasy"],
    status: "ongoing",
    views: 620000
  },
  {
    title: "Cyberpunk: Edgerunners",
    description: "Night City is a sprawling, dangerous metropolis full of cyber-enhanced individuals where one's life is only worth as much as the chrome they are rocking. Life for David Martinez is difficult; he is struggling to make ends meet and keep up with his high-end school.",
    year: 2022,
    rating: 8.8,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx120377-2qV23ZJ1LpUu.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/120377-qD1K22P6D40k.jpg",
    genres: ["Action", "Sci-Fi", "Drama"],
    status: "completed",
    views: 1100000
  },
  {
    title: "serial experiments lain",
    description: "Lain Iwakura is an awkward and isolated fourteen-year-old girl who receives an email from a deceased classmate. Upon opening it, Lain is drawn directly into the Wired, a complex global virtual network of communication that blurs boundaries of reality.",
    year: 1998,
    rating: 8.0,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx339-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/339-7Xm9O8vW3L4z.jpg",
    genres: ["Drama", "Mystery", "Psychological", "Sci-Fi", "Supernatural"],
    status: "completed",
    views: 180000 // Cult Classic
  },
  {
    title: "Ergo Proxy",
    description: "Within the domed city of Romdo, humans and androids coexist in a completely controlled environment. When a series of brutal murders by infected androids shakes the society's structure, investigator Re-l Mayer uncovers dark truths.",
    year: 2006,
    rating: 7.9,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx790-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/790-7Xm9O8vW3L4z.jpg",
    genres: ["Mystery", "Psychological", "Sci-Fi", "Thriller"],
    status: "completed",
    views: 140000 // Underrated SciFi
  },
  {
    title: "Ghost in the Shell: Stand Alone Complex",
    description: "In a future where cybernetic technology has advanced completely, Major Motoko Kusanagi and Section 9 investigate complex international cyber-terrorism cases, political corruption schemes, and high-stakes computer hacking crimes.",
    year: 2002,
    rating: 8.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx467-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/467-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Sci-Fi", "Mystery"],
    status: "completed",
    views: 190000
  },
  {
    title: "Pluto",
    description: "The world-famous Swiss robot Montblanc is brutally destroyed. Meanwhile, a prominent robotic rights activist is murdered. European Union detective Gesicht is assigned to solve these linked crimes, discovering that someone is targeting the world's most advanced artificial life forms.",
    year: 2023,
    rating: 8.6,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx145788-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/145788-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Mystery", "Sci-Fi", "Thriller"],
    status: "completed",
    views: 310000
  },
  {
    title: "Akame ga Kill!",
    description: "Tatsumi is a naive country boy who journeys to the Capital to raise funds for his impoverished village. He uncovers extreme systemic corruption and is recruited into Night Raid, an elite covert assassination squad of the Revolutionary Army.",
    year: 2014,
    rating: 7.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20613-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20613-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Drama", "Fantasy"],
    status: "completed",
    views: 1100000
  },
  {
    title: "Hell's Paradise",
    description: "Gabimaru the Hollow is a ruthless ninja assassin sentenced to death execution. He is offered an absolute pardon if he can secure the legendary Elixir of Life from a sinister, unknown paradise island filled with monstrous creations.",
    year: 2023,
    rating: 8.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx128893-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/128893-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Fantasy"],
    status: "ongoing",
    views: 540000
  },
  {
    title: "Slam Dunk",
    description: "Hanamichi Sakuragi is a notorious hot-headed delinquent who has been rejected by fifty girls in middle school. Upon entering high school, he joins the basketball team solely to impress a girl, only to discover a profound passion for the sport.",
    year: 1993,
    rating: 8.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx170-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/170-7Xm9O8vW3L4z.jpg",
    genres: ["Sports", "Comedy", "Drama"],
    status: "completed",
    views: 290000
  },
  {
    title: "Blue Lock",
    description: "Following a catastrophic exit from the 2018 World Cup, the Japanese Football Association initiates a radical training experiment known as Blue Lock, gathering 300 elite high school strikers into a prison-like facility to cultivate the ultimate egoist forward.",
    year: 2022,
    rating: 8.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx143087-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/143087-7Xm9O8vW3L4z.jpg",
    genres: ["Sports", "Action", "Thriller"],
    status: "ongoing",
    views: 780000
  },
  {
    title: "Ao Ashi",
    description: "Ashito Aoi is a talented but rough-around-the-edges middle school football player from an obscure rural town. His immense potential for spatial awareness is noticed by a prominent Tokyo youth club manager, who invites him to professional tryouts.",
    year: 2022,
    rating: 8.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx143023-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/143023-7Xm9O8vW3L4z.jpg",
    genres: ["Sports", "Drama"],
    status: "completed",
    views: 190000
  },
  {
    title: "Run with the Wind",
    description: "Kakeru is a former elite high school runner who is caught shoplifting food. He is rescued by Haiji, an ambitious university student who convinces him to move into a rundown dormitory with eight other residents, aiming to compete in the legendary Hakone Ekiden marathon.",
    year: 2018,
    rating: 8.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101908-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/101908-7Xm9O8vW3L4z.jpg",
    genres: ["Sports", "Drama", "Comedy"],
    status: "completed",
    views: 175000 // Underrated Sports Drama
  },
  {
    title: "KonoSuba: God's Blessing on This Wonderful World!",
    description: "After dying a laughable and pathetic death on his way back from buying a game, high school student Kazuma Satou finds himself sitting before a beautiful goddess named Aqua, who offers him reincarnation in a fantasy world.",
    year: 2016,
    rating: 8.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21202-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21202-7Xm9O8vW3L4z.jpg",
    genres: ["Adventure", "Comedy", "Fantasy", "Isekai"],
    status: "ongoing",
    views: 1100000
  },
  {
    title: "Mushoku Tensei: Jobless Reincarnation",
    description: "A 34-year-old underachieving NEET is killed in a traffic accident and finds himself reincarnated in a magical fantasy world as an infant named Rudeus Greyrat. Retaining his memories, he resolves to live a successful life without regrets.",
    year: 2021,
    rating: 8.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx108465-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/108465-7Xm9O8vW3L4z.jpg",
    genres: ["Drama", "Fantasy", "Isekai"],
    status: "ongoing",
    views: 850000
  },
  {
    title: "No Game No Life",
    description: "Sora and Shiro are inseparable step-siblings who dominate the online gaming world as an undefeated team known as Blank. They view the real world as a garbage game until a god summons them to an alternate realm where all disputes are settled by high-stakes games.",
    year: 2014,
    rating: 8.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx19815-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/19815-7Xm9O8vW3L4z.jpg",
    genres: ["Adventure", "Comedy", "Fantasy"],
    status: "completed",
    views: 1250000
  },
  {
    title: "The Rising of the Shield Hero",
    description: "Naofumi Iwatani is summoned to a parallel world along with three other young men to become the nation's Cardinal Heroes. Armed with only a defensive shield, Naofumi is betrayed, falsely accused, and mocked, forcing him to rise from absolute rock bottom.",
    year: 2019,
    rating: 7.9,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx99263-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/99263-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Fantasy", "Isekai"],
    status: "ongoing",
    views: 910000
  },
  {
    title: "Dr. STONE",
    description: "After five years of harboring unspoken feelings, high school student Taiju Ooki is finally ready to confess his love to Yuzuriha Ogawa. Suddenly, a blinding green light strikes the Earth, petrifying all of humanity into solid stone statues for thousands of years.",
    year: 2019,
    rating: 8.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx105333-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/105333-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Sci-Fi", "Comedy"],
    status: "completed",
    views: 980000
  },
  {
    title: "Fire Force",
    description: "Spontaneous Human Combustion is a terrifying phenomenon that transforms ordinary citizens into blazing, mindless monsters known as Infernals. The Special Fire Force is created to combat these threats, featuring Shinra Kusakabe, a youth who can ignite his feet at will.",
    year: 2019,
    rating: 7.9,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx107112-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/107112-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Sci-Fi", "Supernatural"],
    status: "completed",
    views: 780000
  },
  {
    title: "Soul Eater",
    description: "Death Weapon Meister Academy is a technical institute headed by the Shinigami Lord Death himself. Its mission is to raise powerful Weapons—humans capable of transforming into demon armaments—and Meisters who wield them to harvest corrupt souls.",
    year: 2008,
    rating: 7.9,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx3588-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/3588-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Comedy", "Fantasy", "Supernatural"],
    status: "completed",
    views: 580000
  },
  {
    title: "Noragami Aragoto",
    description: "The second season of Noragami dives deep into the dark history between the minor delivery god Yato and the powerful Goddess of War, Bishamon, revealing historical betrayals, secret plots, and high-stakes cosmic warfare.",
    year: 2015,
    rating: 8.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21128-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21128-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Comedy", "Supernatural"],
    status: "completed",
    views: 790000
  },
  {
    title: "Dororo",
    description: "A samurai lord barters away his newborn son's organs to forty-eight demons in exchange for absolute battlefield dominance. The abandoned, malformed child survives thanks to a medicine man and grows up hunting down demons to reclaim his stolen body.",
    year: 2019,
    rating: 8.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101347-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/101347-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Drama", "Supernatural"],
    status: "completed",
    views: 490000
  },
  {
    title: "ReLIFE",
    description: "Arata Kaizaki is a 27-year-old unemployed loser who fails every job interview. His miserable life changes when an experimental research institute offers him a drug that transforms his appearance back into an 17-year-old to re-attend high school.",
    year: 2016,
    rating: 8.0,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21511-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21511-7Xm9O8vW3L4z.jpg",
    genres: ["Comedy", "Drama", "Romance", "Slice of Life"],
    status: "completed",
    views: 410000
  },
  {
    title: "Horimiya",
    description: "Kyouko Hori is an elite, popular high school girl, while Izumi Miyamura is a gloomy, distant classmate. When a chance encounter outside school reveals their vastly different, hidden private personas, an unlikely sweet friendship sparks.",
    year: 2021,
    rating: 8.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx124080-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/124080-7Xm9O8vW3L4z.jpg",
    genres: ["Comedy", "Romance", "Slice of Life"],
    status: "completed",
    views: 840000
  },
  {
    title: "Maid Sama!",
    description: "Misaki Ayuzawa is the strict student council president of a recently co-ed high school, working tirelessly to protect female students. She harbors a massive secret: she works part-time at a maid cafe, which is discovered by the school's heartthrob.",
    year: 2010,
    rating: 8.0,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx7054-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/7054-7Xm9O8vW3L4z.jpg",
    genres: ["Comedy", "Romance"],
    status: "completed",
    views: 610000
  },
  {
    title: "Fruits Basket (2019)",
    description: "Tooru Honda is an optimistic orphan high school girl who ends up living in a tent on land belonging to the mysterious Souma family. When they discover her setup, they take her in, but she quickly uncovers their dark family secret: they turn into Chinese Zodiac animals when hugged by the opposite sex.",
    year: 2019,
    rating: 8.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx105334-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/105334-7Xm9O8vW3L4z.jpg",
    genres: ["Comedy", "Drama", "Romance", "Supernatural"],
    status: "completed",
    views: 520000
  },
  {
    title: "Ouran High School Host Club",
    description: "Haruhi Fujioka is a brilliant scholarship student at the elite Ouran Academy. While looking for a quiet study space, she stumbles upon the cross-dressing male Host Club and accidentally breaks a massive, incredibly expensive antique vase, forcing her to work as a host.",
    year: 2006,
    rating: 8.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx853-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/853-7Xm9O8vW3L4z.jpg",
    genres: ["Comedy", "Romance"],
    status: "completed",
    views: 540000
  },
  {
    title: "Grand Blue Dreaming",
    description: "Iori Kitahara moves to the coastal town of Izu to attend university, staying at his uncle's scuba diving shop, Grand Blue. He envisions a college life full of beautiful girls, but is quickly swept into a chaotic club culture of drinking and diving.",
    year: 2018,
    rating: 8.3,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx100922-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/100922-7Xm9O8vW3L4z.jpg",
    genres: ["Comedy", "Slice of Life"],
    status: "completed",
    views: 430000
  },
  {
    title: "Daily Lives of High School Boys",
    description: "A completely hilarious look into the mundane, unexciting daily lives of Tadakuni, Hidenori, and Yoshitake—three average students at the all-boys Sanada North High School as they navigate random teenage delusions.",
    year: 2012,
    rating: 8.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11843-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/11843-7Xm9O8vW3L4z.jpg",
    genres: ["Comedy", "Slice of Life"],
    status: "completed",
    views: 390000
  },
  {
    title: "Asobi Asobase",
    description: "Three female middle school classmates form the 'Pastimers Club' to indulge in various traditional and bizarre playground games, leading to absolutely unhinged, screaming comedic dynamics.",
    year: 2018,
    rating: 8.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101001-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/101001-7Xm9O8vW3L4z.jpg",
    genres: ["Comedy", "Slice of Life"],
    status: "completed",
    views: 240000
  },
  {
    title: "Another",
    description: "In 1972, a popular student in Yomiyama North Middle School's class 3-3 passed away. Twenty-six years later, transfer student Kouichi Sakakibara senses a deeply ominous atmosphere gripping his class, centered around a quiet girl with an eyepatch.",
    year: 2012,
    rating: 7.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11111-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/11111-7Xm9O8vW3L4z.jpg",
    genres: ["Horror", "Mystery", "Supernatural", "Thriller"],
    status: "completed",
    views: 890000
  },
  {
    title: "Shiki",
    description: "When a bizarre series of sudden deaths plagues the quiet rural village of Sotoba during a scorching summer, local doctor Toshio Ozaki suspects an epidemic, only to discover a terrifying vampire infestation instead.",
    year: 2010,
    rating: 7.8,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx7724-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/7724-7Xm9O8vW3L4z.jpg",
    genres: ["Horror", "Mystery", "Supernatural", "Thriller"],
    status: "completed",
    views: 210000 // Cult Horror
  },
  {
    title: "Elfen Lied",
    description: "Lucy is a special breed of human known as a Diclonius, armed with short telekinetic invisible arms. She escapes a brutal government research laboratory facility, sustaining a head injury that splits her persona into a helpless child.",
    year: 2004,
    rating: 7.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx226-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/226-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Drama", "Horror", "Psychological", "Sci-Fi"],
    status: "completed",
    views: 540000
  },
  {
    title: "Higurashi: When They Cry",
    description: "Keiichi Maebara moves to the quiet village of Hinamizawa, quickly becoming friends with local schoolmates. However, beneath the village's peaceful facade lies a dark annual festival cycle of brutal murder and mysterious disappearances.",
    year: 2006,
    rating: 7.9,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx934-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/934-7Xm9O8vW3L4z.jpg",
    genres: ["Horror", "Mystery", "Psychological", "Thriller"],
    status: "completed",
    views: 310000
  },
  {
    title: "Mirai Nikki",
    description: "Yukiteru Amano is a lonely high school student who logs life events on his phone. He finds himself dragged into a battle royale game organized by the God of Time, where all twelve participants possess unique diaries that predict the future.",
    year: 2011,
    rating: 7.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx10620-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/10620-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Horror", "Mystery", "Psychological", "Thriller"],
    status: "completed",
    views: 1150000
  },
  {
    title: "Deadman Wonderland",
    description: "Ganta Igarashi is a normal middle schooler whose entire class is brutally massacred by a mysterious red entity. Framed for the crime, he is sentenced to Deadman Wonderland, a chaotic prison theme park where inmates fight for survival.",
    year: 2011,
    rating: 7.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx6880-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/6880-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Horror", "Sci-Fi"],
    status: "completed",
    views: 520000
  },
  {
    title: "Re:Creators",
    description: "Souta Mizushino is a student who dreams of creating light novels. Suddenly, iconic fictional heroes, warriors, and villains from popular anime, manga, and video games materialize into the real human world, clashing over their creators' designs.",
    year: 2017,
    rating: 7.9,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx97980-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/97980-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Drama", "Fantasy", "Sci-Fi"],
    status: "completed",
    views: 195000 // Underrated Action
  },
  {
    title: "Tengen Toppa Gurren Lagann",
    description: "Simon and Kamina break out from their oppressive subterranean village using a tiny mechanoid drill weapon. They rise to the surface world, piloting increasingly colossal mecha to wage cosmic war against the tyrannical Beastmen forces.",
    year: 2007,
    rating: 8.7,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx2001-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/2001-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Comedy", "Mecha", "Sci-Fi"],
    status: "completed",
    views: 650000
  },
  {
    title: "Mobile Suit Gundam: Iron-Blooded Orphans",
    description: "On a terraformed Mars country, a group of elite child soldiers rebel against their abusive corporate military masters. Mikazuki Augus pilots an ancient, legendary weapon—the Gundam Barbatos—to secure their freedom.",
    year: 2015,
    rating: 8.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21268-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21268-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Drama", "Mecha", "Sci-Fi"],
    status: "completed",
    views: 260000
  },
  {
    title: "86 EIGHTY-SIX",
    description: "The Republic of San Magnolia claims their war against the neighboring Empire has zero casualties, fought completely by automated drones. In reality, the automated weapons are piloted by marginalized, human citizens known as the Eighty-Six.",
    year: 2021,
    rating: 8.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx116589-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/116589-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Drama", "Mecha", "Sci-Fi"],
    status: "completed",
    views: 430000
  },
  {
    title: "Aldnoah.Zero",
    description: "The discovery of an ancient alien hyper-gate on the Moon allowed humans to colonize Mars, founding the technologically advanced Vers Empire. Decades later, an all-out apocalyptic interplanetary invasion of Earth is launched.",
    year: 2014,
    rating: 7.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20632-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20632-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Mecha", "Sci-Fi"],
    status: "completed",
    views: 310000
  },
  {
    title: "Guilty Crown",
    description: "Following a catastrophic virus outbreak in 2029, Japan falls under the control of a military organization called the GHQ. Shu Ouma acquires an ability called the Right Hand of the King, allowing him to extract weapon manifestations from human souls.",
    year: 2011,
    rating: 7.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx10793-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/10793-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Drama", "Sci-Fi", "Romance"],
    status: "completed",
    views: 520000
  },
  {
    title: "Kabaneri of the Iron Fortress",
    description: "During an industrial revolution country, a mysterious virus transforms humans into aggressive, flesh-eating monsters called Kabane that cannot be destroyed unless their iron-coated hearts are pierced. Survivors live in walled stations connected by massive armored trains.",
    year: 2016,
    rating: 7.6,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21196-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21196-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Drama", "Fantasy", "Horror"],
    status: "completed",
    views: 390000
  },
  {
    title: "Seraph of the End: Vampire Reign",
    description: "A mysterious virus decimates all humans above the age of thirteen, leaving children to be enslaved by a cruel vampire civilization. Yuuichirou Hyakuya escapes captivity and registers in the Imperial Demon Army to exact complete revenge.",
    year: 2015,
    rating: 7.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20829-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20829-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Drama", "Fantasy", "Supernatural"],
    status: "completed",
    views: 620000
  },
  {
    title: "Noragami",
    description: "Yato is a minor deity who styles himself as a delivery god, dreaming of millions of worshippers. Without a single shrine to his name, his fortunes change when a human middle school girl saves him from a car accident, loose bonding their souls.",
    year: 2014,
    rating: 8.0,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20447-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20447-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Comedy", "Supernatural"],
    status: "completed",
    views: 980000
  },
  {
    title: "Akatsuki no Yona",
    description: "Princess Yona enjoys a luxurious, peaceful life in her kingdom until a shocking betrayal by her beloved cousin leaves her father murdered. She is forced to flee with her bodyguard, embarking on a quest to find the four legendary Dragon warriors.",
    year: 2014,
    rating: 8.0,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20770-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20770-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Comedy", "Fantasy", "Romance"],
    status: "completed",
    views: 340000 // Underrated Fantasy Shonen
  },
  {
    title: "Beyond the Boundary",
    description: "Akihito Kanbara is a high school student who appears human but is half-demon with immortal rapid healing. He saves Mirai Kuriyama, a clumsy girl who can manipulate her own blood into a weapon, discovering she is an elite spirit world warrior.",
    year: 2013,
    rating: 7.7,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx18153-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/18153-7Xm9O8vW3L4z.jpg",
    genres: ["Fantasy", "Slice of Life", "Supernatural"],
    status: "completed",
    views: 410000
  },
  {
    title: "Charlotte",
    description: "Yuu Otosaka possesses a secret superpower that allows him to temporarily hijack anyone's body for five seconds. He uses this asset to clear high school exams until he is caught by Nao Tomori, who forces him to join a specialized academy.",
    year: 2015,
    rating: 7.8,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20997-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20997-7Xm9O8vW3L4z.jpg",
    genres: ["Drama", "Supernatural", "Comedy"],
    status: "completed",
    views: 890000
  },
  {
    title: "Angel Beats!",
    description: "Otonashi wakes up in the afterlife with zero memories, finding himself in a high school campus setting designed as a buffer zone for youths who experienced severe trauma before dying. He joins a battle faction rebelling against God's angel.",
    year: 2010,
    rating: 8.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx6547-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/6547-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Comedy", "Drama", "Supernatural"],
    status: "completed",
    views: 790000
  },
  {
    title: "Bungo Stray Dogs",
    description: "Atsushi Nakajima is kicked out of his orphanage and accidentally rescues a strange detective named Osamu Dazai from drowning. He is quickly recruited into the Armed Detective Agency, a team of individuals armed with supernatural literary abilities.",
    year: 2016,
    rating: 8.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21311-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21311-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Mystery", "Supernatural"],
    status: "ongoing",
    views: 650000
  },
  {
    title: "Danganronpa: The Animation",
    description: "Makoto Naegi enters Hope's Peak Academy, an elite high school for exceptional students. However, the students find themselves locked inside by a sinister robotic bear named Monokuma, who forces them to participate in a deadly murder game.",
    year: 2013,
    rating: 7.2,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16592-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/16592-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Mystery", "Psychological"],
    status: "completed",
    views: 480000
  },
  {
    title: "Terror in Resonance",
    description: "Tokyo is completely decimated by a shocking terrorist attack, and the only hint left behind is a cryptic internet video uploaded by two teenage boys who call themselves 'Sphinx'. They challenge the metropolitan police force to a high-stakes puzzle game.",
    year: 2014,
    rating: 8.1,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20661-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20661-7Xm9O8vW3L4z.jpg",
    genres: ["Drama", "Mystery", "Psychological", "Thriller"],
    status: "completed",
    views: 520000
  },
  {
    title: "Ajin: Demi-Human",
    description: "Ajin are mysterious immortal humans who cannot die and possess unique supernatural shadow assets. High schooler Kei Nagai is hit by a truck and revives immediately, finding himself hunted globally by governments wanting to experiment on his body.",
    year: 2016,
    rating: 7.4,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21341-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21341-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Horror", "Mystery", "Supernatural"],
    status: "completed",
    views: 190000
  },
  {
    title: "Tokyo Revenge",
    description: "Takemichi Hanagaki is a freelancer loser who discovers his middle school girlfriend was murdered by the Tokyo Manji Gang. He accidentally travels twelve years back in time, resolving to climb the ranks of the gang to save her future.",
    year: 2021,
    rating: 7.6,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx120120-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/120120-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Drama", "Supernatural"],
    status: "ongoing",
    views: 890000
  },
  {
    title: "Blue Exorcist",
    description: "Rin Okumura is a seemingly ordinary troublesome teenager until he discovers he is actually the literal son of Satan. When his guardian is killed by demons, Rin draws a legendary demon-slaying sword, entering True Cross Academy to become an exorcist.",
    year: 2011,
    rating: 7.5,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx9919-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/9919-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Fantasy", "Supernatural"],
    status: "ongoing",
    views: 810000
  },
  {
    title: "Devilman Crybaby",
    description: "Akira Fudo is a gentle high school boy who tracks down demons with his childhood friend Ryo. He merges with a powerful demon entity named Amon to safeguard humanity, descending into a brutal apocalyptic nightmare.",
    year: 2018,
    rating: 7.8,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx98460-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/98460-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Horror", "Psychological", "Supernatural"],
    status: "completed",
    views: 590000
  },
  {
    title: "Claymore",
    description: "In a world plagued by flesh-eating monsters called Yoma, humanity's only defense is a mysterious order of half-human, half-Yoma female warriors known as Claymores, who carry massive swords to track down hidden monsters.",
    year: 2007,
    rating: 7.7,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1818-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/1818-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Adventure", "Fantasy", "Horror"],
    status: "completed",
    views: 240000
  },
  {
    title: "Darker than Black",
    description: "Ten years ago, an impenetrable anomaly known as Hell's Gate appeared in Tokyo. Concurrently, individuals emerged with supernatural contract abilities at the cost of their human emotions, working as covert espionage operators.",
    year: 2007,
    rating: 7.9,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx2025-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/2025-7Xm9O8vW3L4z.jpg",
    genres: ["Action", "Mystery", "Sci-Fi", "Supernatural"],
    status: "completed",
    views: 380000
  },
  {
    title: "Welcome to the NHK",
    description: "Tatsuhiro Satou is a 22-year-old university dropout who has been a shut-in hikikomori for four years. He develops a wild conspiracy theory that a secret organization is purposefully broadcasting media to turn citizens into lonely NEETS.",
    year: 2006,
    rating: 8.3,
    thumbnail: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1210-8JkKmO2xYn8P.jpg",
    cover: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/1210-7Xm9O8vW3L4z.jpg",
    genres: ["Comedy", "Drama", "Psychological"],
    status: "completed",
    views: 210000 // Cult Classic Psychological
  }
];

mongoose.connect(process.env.MONGODB_URI)
  .then(async () => {
    console.log("Connected to DB. Seeding...");
    await Anime.insertMany(animes);
    console.log("Successfully seeded 153 animes!");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
